apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::162886323179:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::162886323179:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-KX2ZGL6FH14H
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-07-24T10:17:54Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-07-24T10:17:54Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2094"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 14abc1cf-59b2-4ee5-bedd-bfb2bd748904
